[gcloud]
symbol = 'ó°¯½ '
format = 'on [$symbol$account(@$domain) (\($project\))]($style) '

[go]
symbol = 'ó°œ‰ '

[custom.chezmoi]
command = 'echo chezmoi'
when = ''' test "$CHEZMOI" = 1 '''
symbol = 'ğŸ¡'
