[docker_context]
symbol = 'î™ '

[gcloud]
symbol = 'ó°¯½ '
format = 'on [$symbol$account(@$domain) (\($project\))]($style) '

[git_branch]
symbol = 'ï˜ '

[golang]
symbol = 'î˜§ '

[custom.chezmoi]
command = 'echo chezmoi'
when = ''' test "$CHEZMOI" = 1 '''
symbol = 'ğŸ¡'
