[custom.jobcan]
command = 'jobcan status'
when = ''' test -n "$JOBCAN_EMAIL" '''
format = "ğŸ™†"

[custom.gitmail]
command = 'git config user.email'
when = ''' test -d .git '''
format = 'îœ‰ $output '

[custom.chezmoi]
command = 'echo chezmoi'
when = ''' test "$CHEZMOI" = 1 '''
symbol = 'î¬† '

[gcloud]
symbol = 'ó°¬ '
format = '[$symbol$project]($style) '

[aws]
symbol = 'îŒ½  '

[buf]
symbol = 'ï’ '

[c]
symbol = 'î˜ '

[conda]
symbol = 'ï„Œ '

[crystal]
symbol = 'î˜¯ '

[dart]
symbol = 'î˜ '

[directory]
read_only = ' ó°Œ¾'

[docker_context]
symbol = 'ïŒˆ '

[elixir]
symbol = 'î˜­ '

[elm]
symbol = 'î˜¬ '

[fennel]
symbol = 'îš¯ '

[fossil_branch]
symbol = 'ï˜ '

[git_branch]
symbol = 'îœ¥ '

[golang]
symbol = 'î˜§ '

[guix_shell]
symbol = 'ïŒ¥ '

[haskell]
symbol = 'î· '

[haxe]
symbol = 'î™¦ '

[hg_branch]
symbol = 'ï˜ '

[hostname]
ssh_symbol = 'î¬ '

[java]
symbol = 'î‰– '

[julia]
symbol = 'î˜¤ '

[kotlin]
symbol = 'î˜´ '

[lua]
symbol = 'î˜  '

[memory_usage]
symbol = 'ó°› '

[meson]
symbol = 'ó°”· '

[nim]
symbol = 'ó°†¥ '

[nix_shell]
symbol = 'ïŒ“ '

[nodejs]
symbol = 'îœ˜ '

[ocaml]
symbol = 'î™º '

[os.symbols]
Alpaquita = 'îª¢ '
Alpine = 'ïŒ€ '
Amazon = 'ï‰° '
Android = 'ï…» '
Arch = 'ïŒƒ '
Artix = 'ïŒŸ '
CentOS = 'ïŒ„ '
Debian = 'ïŒ† '
DragonFly = 'îŠ '
Emscripten = 'ïˆ… '
EndeavourOS = 'ï†— '
Fedora = 'ïŒŠ '
FreeBSD = 'ïŒŒ '
Garuda = 'ó°›“ '
Gentoo = 'ïŒ '
HardenedBSD = 'ó°Œ '
Illumos = 'ó°ˆ¸ '
Linux = 'ïŒš '
Mabox = 'î¬© '
Macos = 'ïŒ‚ '
Manjaro = 'ïŒ’ '
Mariner = 'ï‡ '
MidnightBSD = 'ï†† '
Mint = 'ïŒ '
NetBSD = 'ï€¤ '
NixOS = 'ïŒ“ '
OpenBSD = 'ó°ˆº '
openSUSE = 'ïŒ” '
OracleLinux = 'ó°Œ· '
Pop = 'ïŒª '
Raspbian = 'ïŒ• '
Redhat = 'ïŒ– '
RedHatEnterprise = 'ïŒ– '
Redox = 'ó°€˜ '
Solus = 'ó° ³ '
SUSE = 'ïŒ” '
Ubuntu = 'ïŒ› '
Unknown = 'ïˆ­ '
Windows = 'ó°² '

[package]
symbol = 'ó°— '

[perl]
symbol = 'î™¾ '

[php]
symbol = 'î˜ˆ '

[pijul_channel]
symbol = 'ï˜ '

[python]
symbol = 'îˆµ '

[rlang]
symbol = 'ó°Ÿ” '

[ruby]
symbol = 'î‘ '

[rust]
symbol = 'î¨ '

[scala]
symbol = 'îœ· '

[swift]
symbol = 'î• '

[terraform]
symbol = 'ó±¢ '

[zig]
symbol = 'îš© '
